### ISSUE TITLE
Close Session Error

### ISSUE THREAD

**Issue by mrdlaaziz** [ajepe/pos_customization#7]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1392, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/point_of_sale/models/pos_session.py", line 287, in action_pos_session_closing_control
    session.action_pos_session_close()
  File "/odoo/odoo-server/addons/point_of_sale/models/pos_session.py", line 318, in action_pos_session_close
    return self._validate_session()
  File "/odoo/odoo-server/addons/point_of_sale/models/pos_session.py", line 336, in _validate_session
    self.with_company(self.company_id)._create_account_move()
  File "/odoo/odoo-server/addons/point_of_sale/models/pos_session.py", line 439, in _create_account_move
    data = self._create_invoice_receivable_lines(data)
  File "/odoo/odoo-server/addons/point_of_sale/models/pos_session.py", line 687, in _create_invoice_receivable_lines
    commercial_partner = partner.commercial_partner_id
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'int' object has no attribute 'commercial_partner_id'

**Comment by ajepe** [comment]
To fix this error I created this module **softlink_pos_customization** I will be fixing base modules issue in the module.

**Comment by ajepe** [comment]
I have updated this on the testing server
